

apiVersion: v1
kind: Service
metadata:
  name: simple-express-service
  labels:
    app: simple-express
spec:
  type: NodePort
  selector:
    app: simple-express
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000