apiVersion: v1
kind: Service
metadata:
  name: simple-express-service
  labels:
    app: simple-express
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  selector:
    app: simple-express